// data/colleges.ts
export const COLLEGES = [
  "Modern College of Arts, Science and Commerce (Autonomous), Shivajinagar",
  "P.E.S. Modern College of Engineering",
  "Modern College of Arts, Science & Commerce, Ganeshkhind",
  "Modern College of Arts, Science & Commerce, Warje",
  "Fergusson College Pune",
  "Abasaheb Garware College",
  "Nowrosjee Wadia College",
  "Sir Parashurambhau College",
  "Savitribai Phule Pune University",
  "PVG'S College Of Engineering, Technology And Management",
  "St. Mira's College For Girls",
  "Dr. D.Y. Patil Institute of Technology, Pimpri",
  "DY Patil International University, Akurdi",
  "Dr. D.Y. Patil Vidyapeeth, Pimpri",
  "Dr. D.Y. Patil Institute of Engineering, Management and Research",
  "Ajeenkya DY Patil University",
  "PCCOE-Pimpri Chinchwad College Of Engineering",
  "MIT World Peace University (MIT-WPU)",
  "MIT Art, Design & Technology University",
  "Symbiosis Institute of Technology (SIT)",
  "Symbiosis International University",
  "COEP Technological University",
  "JSPM University Pune",
  "AISSMS College of Engineering",
  "AISSMS Institute of Information Technology",
  "MARATHWADA MITRAMANDAL COLLEGE OF ENGINEERING",
  "Sinhgad College of Engineering",
  "Dr. D.Y. Patil Arts, Commerce & Science College, Pimpri",
  "New Arts, Commerce and Science College, Ahmednagar",
  "Prin. N.G. Naralkar Institute of Career Development & Research",
  "PDEA ::BGC College, Sangvi, Pune",
  "Baburaoji Gholap College, Sangvi, Pune",
  "Indira College of Commerce & Science (ICCS)",
  "Indira College of Engineering and Management",
  "Jaikranti College of Computer Science and Management Studies",
  "MKSSS's Cummins College of Engineering For Women",
  "Dr. Babasaheb Ambedkar College, Aundh",
  "Haribhai V. Desai College of Commerce, Arts and Science",
  "Pratibha College of Commerce and Computer Studies",
  "AISSMS Polytechnic, Pune",
  "Marathwada Mitra Mandal's College of Commerce",
  "MIT Arts, Commerce & Science College, Alandi",
  "PROF. RAMKRISHNA MORE ARTS, COMMERCE & SCIENCE COLLEGE",
  "Dr. Arvind B. Telang College of Arts, Commerce and Science",
  "Maratha Vidya Prasarak Samaj's Commerce, Management & Computer Science College",
  "JSPM Rajarshi Shahu College Of Engineering, Tathawade",
  "Vishwakarma Institute of Technology (VIT)"
];