export const COURSE = [
  "Arts",
  "Commerce",
  "Science",
  "B.Sc. Computer Science",
  "BCA Science",
  "BBA Computer Application",
  "B.Sc. Data Science",
  "BE",
  "BTech",
  "B.Com",
  "BBA",
  "BA",
  "B.Sc",
  "B.Sc Animation ",
  "B.Voc Animator",
  "M.Sc. Computer Science",
  "M.Sc. Computer Application",
  "MCA",
  "MBA",
  "Diploma in Engineering",
];