import type { Metadata } from "next";
// import { Geist} from "next/font/google";
import "@/app/globals.css";
import { getCurrentUserWithRole } from "@/lib/auth/getCurrentUserWithRole";
import { redirect } from "next/navigation";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default  async function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    const { user , role}= await getCurrentUserWithRole()

    if(!user){
        redirect("/login")
    }
    if(role!=="admin") redirect("/unauthorized")
  return (
    
      <>
        {children}
      </>
  
  );
}
