import type { Metadata } from "next";
// import { Geist} from "next/font/google";
import "@/app/globals.css";
import Header from "@/components/common/header";
import Footer from "@/components/common/footer";
import { ToastContainer } from "react-toastify";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "KRF-MCASC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable}  antialiased`}
      >
        <Header/>
        {children}
        <ToastContainer />
        <Footer/>
      </body>
    </html>
  );
}
